add rate limiting for channel and user fetch
DonDebonair/slack-machine pull request #1115
Opened 2024-08-17 06:16 UTC by sprutner

2024-08-17 14:24 UTC, DonDebonair commented on machine/clients/slack.py
> +    async def fetch_all_users(client):
Can you add type annotations for the function argument and return?

2024-08-17 14:24 UTC, DonDebonair commented on machine/clients/slack.py
> +    async def fetch_all_channels(client) -> List[Dict[str, Any]]:
You can use lowercase `list` and `dict` here. In more recent versions of Python this is the recommended way

2024-08-17 14:28 UTC, DonDebonair commented on machine/clients/slack.py
> +                    logger.error(f"Error fetching channels: {e.response['error']}")
```suggestion
                    logger.error(f"Error fetching users: {e.response['error']}")
```

I would actually rethrow the exception here. If you don't, slack-machine is left with an incomplete list of users which will likely cause all kinds of undesired behavior. In my opionion, slack-machine shouldn't even start when failing to fetch users.

2024-08-17 14:29 UTC, DonDebonair commented on machine/clients/slack.py
> +            except Exception as e:
Why would we catch unknown exceptions? Let them bubble up and crash slack-machine. Easier to debug and as mentioned above, prevents undesired behavior

2024-08-17 14:29 UTC, DonDebonair commented on machine/clients/slack.py
> +                    logger.error(f"Error fetching channels: {e.response['error']}")
Same as above, rethrow exception

2024-08-17 14:29 UTC, DonDebonair commented on machine/clients/slack.py
> +            except Exception as e:
same as above, don't catch exception

2024-08-17 14:30 UTC, DonDebonair requested changes
Hey @sprutner I assume you tested this on your workspace with many users?

I left a few comments to improve the code a bit. Great addition though! Excited to merge this in!

2024-08-17 17:27 UTC, sprutner commented
Yeah I tested it on my workspace with like 68,000 users. It boots but it isn't getting any input from me as a user...perhaps workspace permissions issue. I pushed a couple commits but haven't tested it. I never set the python env up it was just a late night hack. I can look more into cleaning this up over the weekend :)

2024-08-17 17:39 UTC, DonDebonair commented
Yeah it would help if you can do a bit of serious testing :)

2024-08-19 04:13 UTC, sprutner commented
@DonDebonair doesn't seem like your tests run on each commit. It is hard for me to see if it's passing your tests here but re-requesting review. Installed the pre-commit hooks and ran them and got them to pass.

2024-08-19 11:55 UTC, DonDebonair commented
Can you allow me to push to this branch on your fork? It's probably easier for me to fix the MyPy issues and I want to rebase the branch on `main` as well

2024-08-19 17:40 UTC, sprutner commented
@DonDebonair done

2024-11-16 00:10 UTC, jasonwbarnett commented
@sprutner alright to close?

2024-11-16 00:54 UTC, sprutner commented
I think so. I forked this. I have been busy with other projects but when I
come back to this I can make another PR

All Good Things,
Seth Rutner


On Fri, Nov 15, 2024 at 9:11 PM Jason Barnett ***@***.***>
wrote:

> @sprutner <https://github.com/sprutner> alright to close?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DonDebonair/slack-machine/pull/1115#issuecomment-2480190121>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAW7FSYQ3GRALINZGQGIUVD2A2ESPAVCNFSM6AAAAABMVERFJCVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDIOBQGE4TAMJSGE>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2024-11-16 12:53 UTC, DonDebonair commented
@sprutner no need to open a new PR. #1194 done by @jasonwbarnett includes your code.

2024-11-16 12:53 UTC, closed without merging