Sqlite3 backend
DonDebonair/slack-machine pull request #819
Opened 2023-06-09 19:03 UTC by cp-richard

I needed SQLite3 support, and we've been using it for some time.  I have tried to cover all the items I think you would want in a good PR.  Doc and unit test are there, but my skills might be lacking in this area as well as my pyproject usage.

Let me know if there are any changes you want or need in the PR to make it easier to review/merge.

2023-06-11 08:50 UTC, DonDebonair commented
Hey @cp-richard this is a great idea! Let me know if you need any help resolving your MyPy issues.

2023-06-12 05:35 UTC, cp-richard commented
In the spirit of the redis and dynamodb I was keeping it simple.  I only needed it because I was using the RBAC module (IIRC).  It took me too long to get the mypy/tests/and sqlite connection 'best practices' as it was :smile:

Hopefully it's of some use to someone else and makes my personal fork upstream merges easier :+1:

2023-08-05 10:49 UTC, DonDebonair commented on machine/storage/backends/sqlite.py
> +            "SELECT value FROM storage WHERE key=? and (expires > ? OR expires IS NULL)", (key, current_GMT)
`expires > ?` will realistically never hold true as `expires` in the `set(...)` method is the number of seconds from now when the key expires.

Example: 

```python
# This sets a key to be expired 300 seconds from now (i.e. 5 minutes)
set("my-key", b"my-value", 300)`
```

This means that in the `get(...)` method, the comparison that is made is `300 > 1691232468` (the latter is the current epoch time gotten from `time.time()`) which will not be true, even if the key was just set.

The change you need to make, is in the `set(...)` method set the `expires` column to `int(time.time()) + expires`. That will make the `get(...)` method work properly.

2023-08-05 10:50 UTC, DonDebonair commented on machine/storage/backends/sqlite.py
> +            "SELECT EXISTS(SELECT 1 FROM storage WHERE key=? and (expires > ? OR expires IS NULL))", (key, current_GMT)
This will only work if `set(...)` is changed. See comment above.

2023-08-05 10:52 UTC, DonDebonair reviewed
There is an error in the _expires_ logic in your code. See comments. If you fix it, it would be nice to provide a test for this. You can do so by mocking/patching `time.time()`

2023-08-05 10:52 UTC, DonDebonair requested changes
There is an error in the _expires_ logic in your code. See comments. If you fix it, it would be nice to provide a test for this. You can do so by mocking/patching `time.time()`

2023-08-13 14:14 UTC, DonDebonair commented
I wanted to make a few changes, incl. updating the branch with the new stuff on `main` and fixing some variable names. It was easier for me to change them myself than to ask you to do it. Given that I don't have push access to your fork, I created my own PR #844 . You still have commit credits of course.

2023-08-13 14:27 UTC, DonDebonair commented
fixed by #844

2023-08-13 14:27 UTC, closed without merging

2023-08-13 15:53 UTC, DonDebonair commented
Released in [v0.34.0](https://github.com/DonDebonair/slack-machine/releases/tag/v0.34.0)